import os

import genanki
import mnemocards
from mnemocards import ASSETS_DIR
from mnemocards.__main__ import main
from mnemocards.builders import get_builder
from mnemocards.builders.vocabulary_builder import VocabularyBuilder
from mnemocards.utils import get_hash_id, NoteID, generate_card_uuid

from tl import get_translation


def scrape_words_from_file(word_file, data_dir="") -> list[str]:
    filename = os.path.join(data_dir, word_file)
    if not os.path.exists(filename):
        raise Exception("""File with words for TSV generator doesn't exist.
Default file name for words "words.txt".
To get words from file with differen name use key [--word-file WORD_FILE]""")

    with open(filename, "r+") as file:
        words_list = []
        for word in file:
            if "#" not in word:
                words_list.append(word.strip())
    return words_list


css = open(f"{ASSETS_DIR}/css/autogenerate.css").read()
CARD_MODEL = genanki.Model(
    get_hash_id("725b5570-eb22-4ca5-a2b2-817e04514cde"),
    "Autogenerated vocabulary model",
    fields=[
        # Visible fields.
        {"name": "YourLanguageWord"},
        {"name": "YourLanguageExplanation"},
        {"name": "LanguageYouLearnWord"},
        {"name": "LanguageYouLearnPronunciation"},
        {"name": "LanguageYouLearnExplanation"},
        # Configuration fields.
        {"name": "CardColor"},
        {"name": "ShowPronunciationInReverse"},
    ],
    templates=[
        {
            "name": "Vocabulary card",
            "qfmt": '''
                <style>
                    .card {
                        background: {{CardColor}};
                    }
                    .origin {
                        color: black;
                    }
                    .synonyms .line_2 {
                        color: #0000;
                    }
                </style>
                <div class="origin word">{{YourLanguageWord}}</div>
                <div class="origin comment">{{YourLanguageExplanation}}</div>
            ''',
            "afmt": '''
                <style>
                    .card {
                        background: {{CardColor}};
                    }
                    .origin {
                        color: black;
                    }
                    .destination {
                        color: black;
                    }
                </style>
                <div class="origin word">{{YourLanguageWord}}</div>
                <div class="origin comment">{{YourLanguageExplanation}}</div>
                <hr>
                <div class="destination word">{{LanguageYouLearnWord}}</div>
                <div class="destination fonetic">{{LanguageYouLearnPronunciation}}</div>
                <div class="destination comment">{{LanguageYouLearnExplanation}}</div>
            ''',
        },
        {
            "name": "Vocabulary card (reversed)",
            "qfmt": '''
                <style>
                    .card {
                        background: {{CardColor}};
                    }
                    .destination {
                        color: black;
                    }
                    .definitions .line_1{
						color: #0000
					}
		            .definitions .line_2{
						color: #0000
				    }
                </style>
                <div class="destination word">{{LanguageYouLearnWord}}</div>
                {{#ShowPronunciationInReverse}}
                <div class="destination fonetic">{{LanguageYouLearnPronunciation}}</div>
                {{/ShowPronunciationInReverse}}
                <div class="destination comment">{{LanguageYouLearnExplanation}}</div>
            ''',
            "afmt": '''
                <style>
                    .card {
                        background: {{CardColor}};
                    }
                    .origin {
                        color: black;
                    }
                    .destination {
                        color: black;
                    }
                </style>
                <div class="destination word">{{LanguageYouLearnWord}}</div>
                <div class="destination fonetic">{{LanguageYouLearnPronunciation}}</div>
                <div class="destination comment">{{LanguageYouLearnExplanation}}</div>
                <hr>
                <div class="origin word">{{YourLanguageWord}}</div>
                <div class="origin comment">{{YourLanguageExplanation}}</div>
            ''',
        },
    ],
    css=css,
)


class AutogenerateBuilder(VocabularyBuilder, object):

    def __init__(self):
        super().__init__()

    @staticmethod
    def parse_src_to_settings(data_dir, src):
        settings = {"color": src.get("card_color", "#f5f5f5"),
                    "show_p": "true" if src.get("pronunciation_in_reverse", False) else "",
                    "filename": os.path.join(data_dir, src["file"]),
                    "one_translation": src.get("one_translation", False),
                    "card_properties": src.get("card_properties", None), "tags": []}

        if src.get("card_properties", None):
            settings["tags"] = src["card_properties"].get("tags", [])

        return settings

    @staticmethod
    def build_cards_from_words(settings):
        words = scrape_words_from_file(settings["filename"])
        translations = get_translation(words)
        print(words[0])
        print(translations[0])

        cards = [{"card_id": str(generate_card_uuid(trans)), "ylw": trans, "yle": "",
                  "lylw": words[idx], "lylp": "", "lyle": ""} for idx, trans in enumerate(translations)]
        for card in cards:
            card["tags"] = settings["tags"]

        return cards

    @staticmethod
    def build_notes_and_media(settings, cards):
        notes, media = [], []
        for card in cards:

            if settings["one_translation"]:
                card["yle"] = ""

            note = NoteID(
                card["card_id"],
                model=CARD_MODEL,
                fields=[
                    card["ylw"], card["yle"], card["lylw"], card["lylp"],
                    card["lyle"], settings["color"], settings["show_p"]],
                tags=card["tags"])
            notes.append(note)
        return notes, media

    def build_cards(self, data_dir, src, deck_config, clean_audio=True):

        # Get data from config.
        settings = self.parse_src_to_settings(data_dir, src)

        builder = self.build_cards_from_words

        cards = builder(settings)
        #
        notes, media = self.build_notes_and_media(settings, cards)

        return notes, media


# noinspection PyProtectedMember
mnemocards.builders._BUILDERS["autogenerate_am"] = AutogenerateBuilder()
main()
